# Generated by Django 2.2.6 on 2019-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别'),
        ),
    ]
