# Generated by Django 2.2.6 on 2019-10-28 09:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191028_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Students.get_photo, verbose_name='照片'),
        ),
    ]
